In [ ]:
import numpy as np
def elm_fit(x,target,h,W=None):
  if W is None:
    W=np.random.uniform(-1.,1.,(h,len(x[0])))
    
    
  # Hitung output hidden layer  
  Hinit=x@W.T  # T = Transpose
  print(Hinit)  
  print(" ")

  H=1/(1+np.exp(-Hinit))
  print(H)
  print(" ")

  # moore-penrose generalized inverse
  Ht=H.T
  Hp=np.linalg.inv(Ht@H)@Ht
  print(Hp)
  print(" ")


  # menghitung nilai beta
  beta=Hp@target
  print(beta)
  print(" ")

  # error  training
  y=H@beta
  mape=sum(abs(y-target)/target)*1000 / len(target)

  return W, beta, mape

In [ ]:
def elm_predict(X,W,b,round_output=False):
  Hinit=X@W.T
  print(Hinit)
  H=1/(1+np.exp(-Hinit))
  print(H) 
  print("beta {}".format(beta))
  y=H@b
  print(y)
  if round_output:
    y=[int(round(x)) for x in y]
  
  return y



In [ ]:
inputdata=np.array([[1,1,0,0],[0,0,0,1],[0,0,1,1],[1,0,0,0],[0,1,1,0]])
target=np.array([1,2,2,1,2])

In [ ]:
bobot, beta, mape=elm_fit(inputdata,target,2,W=None)

[[ 1.89156145 -0.90010488]
 [ 0.78026145 -0.64035353]
 [ 0.53111564 -0.9659088 ]
 [ 0.96252884 -0.55552373]
 [ 0.67988681 -0.67013643]]
 
[[0.86893346 0.28902895]
 [0.68573646 0.34516663]
 [0.62974328 0.27569671]
 [0.72362784 0.36458381]
 [0.66371343 0.33846629]]
 
[[ 3.25590813 -0.94159937  0.37345282 -1.00396039 -1.04286609]
 [-6.56640057  2.71384508 -0.29220068  2.88703669  2.92242688]]
 
[-0.97007754  7.00877868]
 


In [ ]:
output_dat=np.array([[0,1,0,0],[1,1,1,0],[0,1,1,1],[0,0,1,0]])

In [ ]:
predict=elm_predict(output_dat,bobot,beta,round_output=True)

[[ 0.92903262 -0.34458115]
 [ 1.64241565 -1.22566015]
 [ 1.46014826 -1.31048996]
 [-0.2491458  -0.32555527]]
[[0.71687898 0.41469709]
 [0.83786337 0.2269419 ]
 [0.81155535 0.21240487]
 [0.43803376 0.41932248]]
beta [-0.97007754  7.00877868]
[2.21109193 0.77779314 0.70142709 2.51401178]


In [ ]:
print(predict)

[2, 1, 1, 3]


In [ ]:
from sklearn import datasets
from sklearn.preprocessing import minmax_scale
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris=datasets.load_iris()
X=minmax_scale(iris.data)
Y=iris.target
Y+=1

X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=.3)
W,beta,mape=elm_fit(X_train,Y_train, 5)
print("mape {}".format(mape))

output=elm_predict(X_test,W,beta,round_output=True)
accuracy=accuracy_score(output,Y_test)

print("output= {}".format(output))
print("label= {}".format(Y_test))
print("accuracy= {}".format(accuracy))


[[ 1.43247745e-01 -2.17919985e-01  1.50714467e+00  5.91426435e-01
  -4.72080709e-01]
 [ 8.33065415e-02 -1.25547558e-01  4.60206484e-01  1.36800396e-01
  -1.08519399e-01]
 [ 3.50976851e-02 -1.04581063e-01  3.81861395e-01  1.43069637e-01
  -1.44484114e-01]
 [ 9.57748442e-02 -2.32220072e-01  1.79524120e+00  7.96709267e-01
  -8.17283553e-01]
 [ 4.00169803e-02 -1.13680643e-01  8.16649215e-01  3.49699745e-01
  -2.86305109e-01]
 [ 2.49198247e-02 -7.96319462e-02  3.12256739e-01  1.22395551e-01
  -1.29142889e-01]
 [ 2.53354013e-02 -1.62836393e-01  9.21002372e-01  3.97783290e-01
  -3.16070593e-01]
 [ 5.75439950e-03 -1.08200053e-01  7.41991058e-01  3.43205197e-01
  -3.08666241e-01]
 [ 9.46830452e-02 -1.17679386e-01  6.92577483e-01  2.37779601e-01
  -1.39284839e-01]
 [-8.02443940e-03 -1.10383685e-01  9.67031598e-01  4.72069436e-01
  -4.54586542e-01]
 [-1.09697028e-03 -1.24617693e-01  2.67291501e-01  9.05968974e-02
  -1.09972031e-02]
 [ 1.05623655e-01 -8.25799725e-02  5.11917398e-01  1.69989237e-01